# Generated by Django 3.0.6 on 2020-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Lifestyle', 'Lifestyle'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
